language: android
dist: trusty
install: true
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=30.0.0

android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

branches:
  only:
    - main

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
  - chmod +x gradlew
  - ./gradlew dependencies || true

script:
  # Build App
  - ./gradlew clean :app:assembleRelease --stacktrace

after_script:
  #- chmod +x sign-apk.sh
  #- bash ./sign-apk.sh
  - chmod +x send-to-telegram.sh
  - bash ./send-to-telegram.sh
