sudo: false
install: true
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.0
    - android-28
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'

before_install:
  - chmod +x gradlew
  - ./gradlew dependencies || true
  
script:
  # Build App
  - ./gradlew clean :app:assembleRelease --stacktrace
  # Sign APK
  - cd $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $TRAVIS_BUILD_DIR/app/candybar.jks -storepass candybar -keypass candybar candybar.apk key0
  - jarsigner -verify candybar.apk
  - "${ANDROID_HOME}/build-tools/29.0.0/zipalign -v 4 candybar.apk candybar-signed.apk"

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x send-to-telegram.sh
  - bash ./send-to-telegram.sh
