language: android
dist: trusty
jdk: oraclejdk8
branches:
  only: [main]
env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=30.0.0

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - '.+'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
  - chmod +x gradlew
  - chmod +x send-telegram.sh
script:
  - ./gradlew --no-daemon clean :app:assembleRelease --stacktrace
after_success:
  - bash ./send-telegram.sh
